name: flutter_application_maladie
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Use material design
  uses-material-design: true

  # Specify assets
  assets:
    - lib/assets/image.png
    - lib/assets/
